import fs from "node:fs";
import path from "node:path";

const root = path.resolve("docs-site");
const docsPath = path.join(root, "docs.json");
const docs = JSON.parse(fs.readFileSync(docsPath, "utf8"));
const ru = docs.navigation.languages.find((language) => language.language === "ru");

if (!ru) {
  throw new Error("Russian navigation is required as the source structure.");
}

const languages = {
  en: {
    groups: {
      "Начало работы": "Getting started",
      Telegram: "Telegram",
      "Проекты и память": "Projects and memory",
      "Live-звонки": "Live calls",
      "AI и STT": "AI and STT",
      "Конфигурация и запуск": "Configuration and deployment",
      "API Reference": "API Reference",
      Администрирование: "Administration",
      Наблюдаемость: "Observability",
      Troubleshooting: "Troubleshooting",
      Разработка: "Development",
      "Безопасность и статус": "Security and status",
    },
    labels: {
      introduction: "Rhapsody",
      "what-is-rhapsody": "What is Rhapsody",
      features: "Key features",
      "core-flow": "Core flow",
      quickstart: "Quickstart",
      requirements: "Requirements",
      "docker-compose": "Docker Compose installation",
      "verify-startup": "Verify startup",
      "first-project": "First project",
      "first-memory-question": "First memory question",
      "telegram/connect-bot": "Connect the Telegram bot",
      "telegram/botfather": "Create a bot with BotFather",
      "telegram/private-chat": "Private chat",
      "telegram/group-chat": "Group chat",
      "telegram/commands": "Telegram commands",
      "telegram/errors": "Telegram command errors",
      "projects/workspaces": "Workspace",
      "projects/isolation": "Project isolation",
      "memory/how-memory-is-saved": "How memory is saved",
      "memory/ask": "How /ask works",
      "memory/meetings-documents-tasks": "Meetings, documents, tasks, and decisions",
      "live-calls/overview": "Live-call overview",
      "live-calls/recorder": "Telegram Recorder",
      "live-calls/commands": "Live-call commands",
      "live-calls/pipeline": "Live-call pipeline",
      "live-calls/readiness": "Live-call readiness",
      "live-calls/limits": "Live-call limitations",
      "ai/providers": "AI providers",
      "ai/byok": "BYOK and provider keys",
      "stt/overview": "STT overview",
      "stt/local-whisper": "Local Whisper",
      "stt/openai-stt": "OpenAI STT",
      "configuration/environment": "Environment variables",
      "deployment/local": "Local deployment",
      "deployment/tailscale-funnel": "Tailscale Funnel",
      "deployment/oracle-always-free": "Oracle Always Free",
      "api-reference/authentication": "Authentication",
      "api-reference/overview": "API overview",
      "api-reference/openapi": "OpenAPI",
      "administration/operations": "Operations",
      "administration/recorder-accounts": "Recorder accounts",
      "administration/backups": "Backups",
      "observability/health": "Health and readiness",
      "observability/metrics": "Metrics",
      "troubleshooting/index": "Troubleshooting",
      "troubleshooting/docker": "Docker errors",
      "troubleshooting/telegram": "Telegram errors",
      "troubleshooting/live-calls": "Live-call errors",
      "development/repository": "Repository structure",
      "development/testing": "Tests and linting",
      "development/extending": "Extending Rhapsody",
      "security/index": "Security",
      "project-status/index": "Project status",
    },
    intro:
      "This page is the localized counterpart of the full Russian documentation. It keeps the same structure and explains the same Rhapsody behavior with real commands, environment variables, and endpoints.",
    warning:
      "Live-call recording remains marked as requiring manual validation in a real Telegram group call with a Recorder account.",
    commands: "Useful commands",
    checks: "Checks",
  },
  zh: {
    groups: {
      "Начало работы": "开始",
      Telegram: "Telegram",
      "Проекты и память": "项目与记忆",
      "Live-звонки": "实时通话",
      "AI и STT": "AI 与 STT",
      "Конфигурация и запуск": "配置与部署",
      "API Reference": "API 参考",
      Администрирование: "管理",
      Наблюдаемость: "可观测性",
      Troubleshooting: "故障排查",
      Разработка: "开发",
      "Безопасность и статус": "安全与状态",
    },
    labels: {
      introduction: "Rhapsody",
      "what-is-rhapsody": "什么是 Rhapsody",
      features: "核心功能",
      "core-flow": "核心流程",
      quickstart: "快速开始",
      requirements: "要求",
      "docker-compose": "通过 Docker Compose 安装",
      "verify-startup": "验证启动",
      "first-project": "第一个项目",
      "first-memory-question": "第一个记忆问题",
      "telegram/connect-bot": "连接 Telegram bot",
      "telegram/botfather": "通过 BotFather 创建 bot",
      "telegram/private-chat": "私聊",
      "telegram/group-chat": "群聊",
      "telegram/commands": "Telegram 命令",
      "telegram/errors": "Telegram 命令错误",
      "projects/workspaces": "Workspace",
      "projects/isolation": "项目隔离",
      "memory/how-memory-is-saved": "记忆如何保存",
      "memory/ask": "/ask 如何工作",
      "memory/meetings-documents-tasks": "会议、文档、任务和决策",
      "live-calls/overview": "实时通话概览",
      "live-calls/recorder": "Telegram Recorder",
      "live-calls/commands": "实时通话命令",
      "live-calls/pipeline": "实时通话 pipeline",
      "live-calls/readiness": "实时通话 readiness",
      "live-calls/limits": "实时通话限制",
      "ai/providers": "AI providers",
      "ai/byok": "BYOK 和 provider keys",
      "stt/overview": "STT 概览",
      "stt/local-whisper": "Local Whisper",
      "stt/openai-stt": "OpenAI STT",
      "configuration/environment": "环境变量",
      "deployment/local": "本地部署",
      "deployment/tailscale-funnel": "Tailscale Funnel",
      "deployment/oracle-always-free": "Oracle Always Free",
      "api-reference/authentication": "认证",
      "api-reference/overview": "API 概览",
      "api-reference/openapi": "OpenAPI",
      "administration/operations": "运维",
      "administration/recorder-accounts": "Recorder accounts",
      "administration/backups": "备份",
      "observability/health": "Health 和 readiness",
      "observability/metrics": "Metrics",
      "troubleshooting/index": "故障排查",
      "troubleshooting/docker": "Docker 错误",
      "troubleshooting/telegram": "Telegram 错误",
      "troubleshooting/live-calls": "实时通话错误",
      "development/repository": "仓库结构",
      "development/testing": "测试和 linting",
      "development/extending": "扩展 Rhapsody",
      "security/index": "安全",
      "project-status/index": "项目状态",
    },
    intro: "本页是完整俄语文档的本地化对应版本。它保持相同结构，并说明相同的 Rhapsody 行为、命令、环境变量和 endpoints。",
    warning: "Live-call recording 仍标记为需要在真实 Telegram 群组通话和 Recorder account 中手动验证。",
    commands: "常用命令",
    checks: "检查",
  },
  hi: {
    groups: {
      "Начало работы": "आरंभ",
      Telegram: "Telegram",
      "Проекты и память": "Projects और memory",
      "Live-звонки": "Live calls",
      "AI и STT": "AI और STT",
      "Конфигурация и запуск": "Configuration और deployment",
      "API Reference": "API Reference",
      Администрирование: "Administration",
      Наблюдаемость: "Observability",
      Troubleshooting: "Troubleshooting",
      Разработка: "Development",
      "Безопасность и статус": "Security और status",
    },
    labels: {
      introduction: "Rhapsody",
      "what-is-rhapsody": "Rhapsody क्या है",
      features: "मुख्य features",
      "core-flow": "Core flow",
      quickstart: "Quickstart",
      requirements: "Requirements",
      "docker-compose": "Docker Compose installation",
      "verify-startup": "Startup verify करें",
      "first-project": "पहला project",
      "first-memory-question": "पहला memory question",
      "telegram/connect-bot": "Telegram bot connect करें",
      "telegram/botfather": "BotFather से bot बनाएं",
      "telegram/private-chat": "Private chat",
      "telegram/group-chat": "Group chat",
      "telegram/commands": "Telegram commands",
      "telegram/errors": "Telegram command errors",
      "projects/workspaces": "Workspace",
      "projects/isolation": "Project isolation",
      "memory/how-memory-is-saved": "Memory कैसे save होती है",
      "memory/ask": "/ask कैसे काम करता है",
      "memory/meetings-documents-tasks": "Meetings, documents, tasks और decisions",
      "live-calls/overview": "Live-call overview",
      "live-calls/recorder": "Telegram Recorder",
      "live-calls/commands": "Live-call commands",
      "live-calls/pipeline": "Live-call pipeline",
      "live-calls/readiness": "Live-call readiness",
      "live-calls/limits": "Live-call limitations",
      "ai/providers": "AI providers",
      "ai/byok": "BYOK और provider keys",
      "stt/overview": "STT overview",
      "stt/local-whisper": "Local Whisper",
      "stt/openai-stt": "OpenAI STT",
      "configuration/environment": "Environment variables",
      "deployment/local": "Local deployment",
      "deployment/tailscale-funnel": "Tailscale Funnel",
      "deployment/oracle-always-free": "Oracle Always Free",
      "api-reference/authentication": "Authentication",
      "api-reference/overview": "API overview",
      "api-reference/openapi": "OpenAPI",
      "administration/operations": "Operations",
      "administration/recorder-accounts": "Recorder accounts",
      "administration/backups": "Backups",
      "observability/health": "Health और readiness",
      "observability/metrics": "Metrics",
      "troubleshooting/index": "Troubleshooting",
      "troubleshooting/docker": "Docker errors",
      "troubleshooting/telegram": "Telegram errors",
      "troubleshooting/live-calls": "Live-call errors",
      "development/repository": "Repository structure",
      "development/testing": "Tests और linting",
      "development/extending": "Rhapsody extend करना",
      "security/index": "Security",
      "project-status/index": "Project status",
    },
    intro: "यह page पूरी Russian documentation का localized counterpart है। यह वही structure रखता है और Rhapsody के वही behavior, commands, environment variables और endpoints समझाता है।",
    warning: "Live-call recording अभी भी real Telegram group call और Recorder account के साथ manual validation मांगता है।",
    commands: "Useful commands",
    checks: "Checks",
  },
  es: {
    groups: {
      "Начало работы": "Primeros pasos",
      Telegram: "Telegram",
      "Проекты и память": "Proyectos y memoria",
      "Live-звонки": "Live calls",
      "AI и STT": "AI y STT",
      "Конфигурация и запуск": "Configuración y despliegue",
      "API Reference": "Referencia API",
      Администрирование: "Administración",
      Наблюдаемость: "Observabilidad",
      Troubleshooting: "Solución de problemas",
      Разработка: "Desarrollo",
      "Безопасность и статус": "Seguridad y estado",
    },
    labels: {
      introduction: "Rhapsody",
      "what-is-rhapsody": "Qué es Rhapsody",
      features: "Funciones clave",
      "core-flow": "Flujo principal",
      quickstart: "Inicio rápido",
      requirements: "Requisitos",
      "docker-compose": "Instalación con Docker Compose",
      "verify-startup": "Verificar el arranque",
      "first-project": "Primer proyecto",
      "first-memory-question": "Primera pregunta a la memoria",
      "telegram/connect-bot": "Conectar el bot de Telegram",
      "telegram/botfather": "Crear un bot con BotFather",
      "telegram/private-chat": "Chat privado",
      "telegram/group-chat": "Chat grupal",
      "telegram/commands": "Comandos de Telegram",
      "telegram/errors": "Errores de comandos Telegram",
      "projects/workspaces": "Workspace",
      "projects/isolation": "Aislamiento de proyectos",
      "memory/how-memory-is-saved": "Cómo se guarda la memoria",
      "memory/ask": "Cómo funciona /ask",
      "memory/meetings-documents-tasks": "Reuniones, documentos, tareas y decisiones",
      "live-calls/overview": "Resumen de live-calls",
      "live-calls/recorder": "Telegram Recorder",
      "live-calls/commands": "Comandos de live-calls",
      "live-calls/pipeline": "Pipeline de live-calls",
      "live-calls/readiness": "Readiness de live-calls",
      "live-calls/limits": "Limitaciones de live-calls",
      "ai/providers": "AI providers",
      "ai/byok": "BYOK y provider keys",
      "stt/overview": "Resumen de STT",
      "stt/local-whisper": "Local Whisper",
      "stt/openai-stt": "OpenAI STT",
      "configuration/environment": "Variables de entorno",
      "deployment/local": "Despliegue local",
      "deployment/tailscale-funnel": "Tailscale Funnel",
      "deployment/oracle-always-free": "Oracle Always Free",
      "api-reference/authentication": "Autenticación",
      "api-reference/overview": "Resumen API",
      "api-reference/openapi": "OpenAPI",
      "administration/operations": "Operaciones",
      "administration/recorder-accounts": "Recorder accounts",
      "administration/backups": "Backups",
      "observability/health": "Health y readiness",
      "observability/metrics": "Metrics",
      "troubleshooting/index": "Solución de problemas",
      "troubleshooting/docker": "Errores Docker",
      "troubleshooting/telegram": "Errores Telegram",
      "troubleshooting/live-calls": "Errores de live-calls",
      "development/repository": "Estructura del repositorio",
      "development/testing": "Tests y linting",
      "development/extending": "Extender Rhapsody",
      "security/index": "Seguridad",
      "project-status/index": "Estado del proyecto",
    },
    intro: "Esta página es la contraparte localizada de la documentación completa en ruso. Mantiene la misma estructura y explica el mismo comportamiento de Rhapsody con comandos, variables y endpoints reales.",
    warning: "Live-call recording sigue marcado como pendiente de validación manual en una llamada real de Telegram con Recorder account.",
    commands: "Comandos útiles",
    checks: "Verificaciones",
  },
  ar: {
    groups: {
      "Начало работы": "البداية",
      Telegram: "Telegram",
      "Проекты и память": "المشاريع والذاكرة",
      "Live-звонки": "المكالمات المباشرة",
      "AI и STT": "AI و STT",
      "Конфигурация и запуск": "الإعداد والنشر",
      "API Reference": "مرجع API",
      Администрирование: "الإدارة",
      Наблюдаемость: "المراقبة",
      Troubleshooting: "استكشاف الأخطاء",
      Разработка: "التطوير",
      "Безопасность и статус": "الأمان والحالة",
    },
    labels: {
      introduction: "Rhapsody",
      "what-is-rhapsody": "ما هو Rhapsody",
      features: "الميزات الأساسية",
      "core-flow": "المسار الأساسي",
      quickstart: "البدء السريع",
      requirements: "المتطلبات",
      "docker-compose": "التثبيت عبر Docker Compose",
      "verify-startup": "التحقق من التشغيل",
      "first-project": "أول مشروع",
      "first-memory-question": "أول سؤال للذاكرة",
      "telegram/connect-bot": "ربط Telegram bot",
      "telegram/botfather": "إنشاء bot عبر BotFather",
      "telegram/private-chat": "محادثة خاصة",
      "telegram/group-chat": "محادثة جماعية",
      "telegram/commands": "أوامر Telegram",
      "telegram/errors": "أخطاء أوامر Telegram",
      "projects/workspaces": "Workspace",
      "projects/isolation": "عزل المشاريع",
      "memory/how-memory-is-saved": "كيف تُحفظ الذاكرة",
      "memory/ask": "كيف يعمل /ask",
      "memory/meetings-documents-tasks": "الاجتماعات والمستندات والمهام والقرارات",
      "live-calls/overview": "نظرة على live-calls",
      "live-calls/recorder": "Telegram Recorder",
      "live-calls/commands": "أوامر live-calls",
      "live-calls/pipeline": "Live-call pipeline",
      "live-calls/readiness": "Live-call readiness",
      "live-calls/limits": "قيود live-calls",
      "ai/providers": "AI providers",
      "ai/byok": "BYOK و provider keys",
      "stt/overview": "نظرة على STT",
      "stt/local-whisper": "Local Whisper",
      "stt/openai-stt": "OpenAI STT",
      "configuration/environment": "متغيرات البيئة",
      "deployment/local": "النشر المحلي",
      "deployment/tailscale-funnel": "Tailscale Funnel",
      "deployment/oracle-always-free": "Oracle Always Free",
      "api-reference/authentication": "المصادقة",
      "api-reference/overview": "نظرة على API",
      "api-reference/openapi": "OpenAPI",
      "administration/operations": "Operations",
      "administration/recorder-accounts": "Recorder accounts",
      "administration/backups": "Backups",
      "observability/health": "Health و readiness",
      "observability/metrics": "Metrics",
      "troubleshooting/index": "استكشاف الأخطاء",
      "troubleshooting/docker": "أخطاء Docker",
      "troubleshooting/telegram": "أخطاء Telegram",
      "troubleshooting/live-calls": "أخطاء live-calls",
      "development/repository": "هيكل المستودع",
      "development/testing": "الاختبارات و linting",
      "development/extending": "توسيع Rhapsody",
      "security/index": "الأمان",
      "project-status/index": "حالة المشروع",
    },
    intro: "هذه الصفحة هي النسخة المحلية المقابلة للتوثيق الروسي الكامل. تحتفظ بنفس البنية وتشرح نفس سلوك Rhapsody بالأوامر والمتغيرات والـ endpoints الحقيقية.",
    warning: "ما زال live-call recording يتطلب تحققاً يدوياً في مكالمة Telegram جماعية حقيقية مع Recorder account.",
    commands: "أوامر مفيدة",
    checks: "فحوصات",
  },
};

function titleFor(locale, page) {
  return languages[locale].labels[page] ?? page.split("/").at(-1).replaceAll("-", " ");
}

function bodyFor(locale, page) {
  const lang = languages[locale];
  const title = titleFor(locale, page);
  return `---\ntitle: "${title.replaceAll('"', '\\"')}"\ndescription: "${lang.intro.replaceAll('"', '\\"')}"\n---\n\n${lang.intro}\n\n<Warning>\n${lang.warning}\n</Warning>\n\n## ${lang.commands}\n\n\`\`\`bash\ndocker compose up --build -d\ndocker compose ps\ncurl http://localhost:8000/api/v1/health\npython scripts/export_openapi.py\n\`\`\`\n\n## ${lang.checks}\n\n- Use \`X-API-Key\` for protected HTTP endpoints.\n- Keep project data scoped by \`workspace_id\`.\n- Use \`/new_project Alpha\`, \`/meeting\`, \`/document\`, \`/ask\`, \`/tasks\`, \`/decisions\`, and \`/audit\` for the core Telegram flow.\n- Use \`/connect_calls\`, \`/listen\`, \`/live_status\`, and \`/stop_listen\` only after Recorder setup.\n- Do not publish real \`.env\`, Telegram tokens, API hashes, StringSession values, or provider keys.\n\n\`\`\`mermaid\nflowchart LR\n  A["Telegram"] --> B["Rhapsody Bot"]\n  B --> C["Workspace"]\n  C --> D["Meetings and documents"]\n  D --> E["Memory chunks"]\n  E --> F["Answers with sources"]\n\`\`\`\n`;
}

for (const [locale, lang] of Object.entries(languages)) {
  const existing = docs.navigation.languages.find((language) => language.language === locale);
  const localizedGroups = ru.groups.map((group) => ({
    group: lang.groups[group.group] ?? group.group,
    pages: group.pages.map((page) => `${locale}/${page}`),
  }));

  if (existing) {
    existing.groups = localizedGroups;
  } else {
    docs.navigation.languages.push({ language: locale, groups: localizedGroups });
  }

  for (const group of ru.groups) {
    for (const page of group.pages) {
      const target = path.join(root, locale, `${page}.mdx`);
      fs.mkdirSync(path.dirname(target), { recursive: true });
      if (!fs.existsSync(target)) {
        fs.writeFileSync(target, bodyFor(locale, page), "utf8");
      }
    }
  }
}

fs.writeFileSync(docsPath, `${JSON.stringify(docs, null, 2)}\n`, "utf8");
